# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\nserverGRPC\"}\n\rLoginResponse\x12&\n\x06status\x18\x01 \x01(\x0b\x32\x16.serverGRPC.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12$\n\x04user\x18\x04 \x01(\x0b\x32\x16.serverGRPC.UserOutput\"Q\n\x11\x43reateUserRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x15\n\ruser_password\x18\x03 \x01(\t\"\x1a\n\nStatusCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"?\n\nUserOutput\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\"I\n\tUserInput\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x15\n\ruser_password\x18\x03 \x01(\t2\x8a\x01\n\x08\x41piUsers\x12\x43\n\nCreateUser\x12\x1d.serverGRPC.CreateUserRequest\x1a\x16.serverGRPC.StatusCode\x12\x39\n\x05Login\x12\x15.serverGRPC.UserInput\x1a\x19.serverGRPC.LoginResponseB\x10Z\x0egen/serverGRPCb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016gen/serverGRPC'
  _globals['_LOGINRESPONSE']._serialized_start=29
  _globals['_LOGINRESPONSE']._serialized_end=154
  _globals['_CREATEUSERREQUEST']._serialized_start=156
  _globals['_CREATEUSERREQUEST']._serialized_end=237
  _globals['_STATUSCODE']._serialized_start=239
  _globals['_STATUSCODE']._serialized_end=265
  _globals['_USEROUTPUT']._serialized_start=267
  _globals['_USEROUTPUT']._serialized_end=330
  _globals['_USERINPUT']._serialized_start=332
  _globals['_USERINPUT']._serialized_end=405
  _globals['_APIUSERS']._serialized_start=408
  _globals['_APIUSERS']._serialized_end=546
# @@protoc_insertion_point(module_scope)
