# Generated by Django 6.0.3 on 2026-03-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('listeners', models.IntegerField(default=0, verbose_name='Кол-во слушателей')),
                ('bio', models.CharField(max_length=258, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, default='artists/default-artist.jpg', null=True, upload_to='artists/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
                'ordering': ['-listeners'],
            },
        ),
    ]
